<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>



</Project>
