global using Xunit;
global using FluentAssertions.Execution;
global using Shared.Tests.Assertions;
global using Shared.Tests.Builders;
global using Shared.Tests.TestData;
global using FluentAssertions;
global using Core.Domain;
global using Core.Domain.Enums;
global using Core.Contracts.Employees;